class AllDetails{

public static void main(string[]args)
{
System.out.println(Alexa.founder);
System.out.println(Alexa.launchYear);
System.out.println(Alexa.type);
System.out.println("**************************");
System.out.println(Blutooth.version);
System.out.println(Blutooth.limit);
System.out.println(Blutooth.isEnabled);
System.out.println("***************************");
System.out.println(WashingMachine.brand);
System.out.println(WashingMachine.waterLoad);
System.out.println(WashingMachine.speed);
System.out.println("****************************");
System.out.println(Mobile.model);
System.out.println(Mobile.sim);
System.out.println(Mobile.storage);
System.out.println("******************************");
System.out.println(Laptop.brand);
System.out.println(Laptop.model);
System.out.println(Laptop.gen);
System.out.println("**************************");
System.out.println(Chair.model);
System.out.println(Chair.legs);
System.out.println(Chair.material);
System.out.println("************************");
System.out.println(Tree.name);
System.out.println(Tree.leaves);
System.out.println(Tree.isFruits);
System.out.println("******************************");
System.out.println(Pen.modle);
System.out.println(Pen.inkLevel);
System.out.println(Pen.tipSize);
System.out.println("*********************");
System.out.println(Home.houseNumber);
System.out.println(Home.floors);
System.out.println(Home.area);
System.out.println("***************************");
System.out.println(Bike.model);
System.out.println(Bike.engineCC);
System.out.println(Bike.fuel);
}
}